sudo: required

language: generic

services:
- docker
env:
  global:
  - secure: travisEncryptedAWS_ACCOUNT_ID
  - secure: travisEncryptedAWS_ACCESS_KEY_ID
  - secure: travisEncryptedAWS_SECRET_ACCESS_KEY

before_install:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  # - ./ecr_credentials.sh
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl # give user access to kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl # move kubectl path to usr/local/bin
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 # install helm
  - chmod 700 get_helm.sh
  - ./get_helm.sh

script:
  - export COMMIT_ID=$(git rev-parse --verify --short HEAD)
  - docker build --no-cache --build-arg GIT_COMMIT=$COMMIT_ID -t helloworld:$COMMIT_ID -t 310228935478.dkr.ecr.us-west-2.amazonaws.com/helloworld:$COMMIT_ID .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: main
  # provider: script
  # script: bash deploy-prod.sh
  # on:
  #   branch: main
